### ISSUE TITLE
I need some examples

### ISSUE THREAD

**Issue by Wulian233** [rdbende/Sun-Valley-messageboxes#3]
How should I add icons? I need some examples.
For example, ask_allow_block.png 
What is the code of?

**Comment by rdbende** [comment]
As I said in the description, this isn't a Tkinter project, and I don't really have plans with it other than including it in sv-ttk, but here's a little example

```py
import tkinter
from dialogs import ask_allow_block

root = tkinter.Tk()

root.tk.call("source", "sun-valley.tcl")
root.tk.call("set_theme", "dark")

icon = tkinter.PhotoImage(file="~/Pictures/foo.png")

ask_allow_block("Spam", "Ham egg", icon=icon)

root.mainloop()
```
